options:
  os-admin-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Admin network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for admin endpoints.
  os-internal-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Internal network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for internal endpoints.
  os-public-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Public network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for public endpoints.
  os-public-hostname:
    type: string
    default:
    description: |
      The hostname or address of the public endpoints created for neutron-api
      in the keystone identity provider.
      .
      This value will be used for public endpoints. For example, an
      os-public-hostname set to 'neutron-api.example.com' with ssl enabled
      will create the following endpoint for neutron-api:
      .
      https://neutron-api.example.com:9696/
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  haproxy-server-timeout:
    type: int
    default: 30000
    description: |
       Server timeout configuration in ms for haproxy, used in HA
       configurations.
  haproxy-client-timeout:
    type: int
    default: 30000
    description: |
       Client timeout configuration in ms for haproxy, used in HA
       configurations.
  haproxy-queue-timeout:
    type: int
    default: 5000
    description: |
       Queue timeout configuration in ms for haproxy, used in HA
       configurations.
  haproxy-connect-timeout:
    type: int
    default: 5000
    description: |
       Connect timeout configuration in ms for haproxy, used in HA
       configurations.
  ssl_cert:
    type: string
    default:
    description: |
      SSL certificate to install and use for API ports.  Setting this value
      and ssl_key will enable reverse proxying, point Glance's entry in the
      Keystone catalog to use https, and override any certficiate and key
      issued by Keystone (if it is configured to do so).
  ssl_key:
    type: string
    default:
    description: SSL key to use with certificate specified as ssl_cert.
  ssl_ca:
    type: string
    default:
    description: |
      SSL CA to use with the certificate and key provided - this is only
      required if you are providing a privately signed ssl_cert and ssl_key.
